export const PERMISSIONS = {
  BENEFICIARY_READ: 'BENEFICIARY_READ',
  BENEFICIARY_CREATE: 'BENEFICIARY_CREATE',
  BENEFICIARY_UPDATE: 'BENEFICIARY_UPDATE',
  BENEFICIARY_DISCHARGE: 'BENEFICIARY_DISCHARGE',

  EMPLOYEE_READ: 'EMPLOYEE_READ',
  EMPLOYEE_CREATE: 'EMPLOYEE_CREATE',
  EMPLOYEE_UPDATE: 'EMPLOYEE_UPDATE',
  EMPLOYEE_TERMINATE: 'EMPLOYEE_TERMINATE',
  EMPLOYEE_REACTIVATE: 'EMPLOYEE_REACTIVATE',

  HOUSE_UNIT_READ: 'HOUSE_UNIT_READ',
  HOUSE_UNIT_CREATE: 'HOUSE_UNIT_CREATE',
  HOUSE_UNIT_UPDATE: 'HOUSE_UNIT_UPDATE',

  ASSIGNMENT_READ: 'ASSIGNMENT_READ',
  ASSIGNMENT_CREATE: 'ASSIGNMENT_CREATE',
  ASSIGNMENT_TERMINATE: 'ASSIGNMENT_TERMINATE',
  ASSIGNMENT_CANCEL: 'ASSIGNMENT_CANCEL',

  USER_READ: 'USER_READ',
  USER_CREATE: 'USER_CREATE',
  USER_UPDATE: 'USER_UPDATE',
  USER_DEACTIVATE: 'USER_DEACTIVATE',
  USER_REACTIVATE: 'USER_REACTIVATE',

  PLACEMENT_READ: 'PLACEMENT_READ',
  PLACEMENT_CREATE: 'PLACEMENT_CREATE',
  PLACEMENT_UPDATE: 'PLACEMENT_UPDATE',
  PLACEMENT_TERMINATE: 'PLACEMENT_TERMINATE',
} as const

export type Permission = keyof typeof PERMISSIONS