spring.application.name=merimna

# === Server Configuration ===
server.port=8080
server.servlet.context-path=/api

# === Database Connection ===
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

# === JPA / Hibernate Configuration ===
spring.jpa.hibernate.ddl-auto=validate

# === Logging ===
spring.jpa.show-sql=false
logging.level.org.hibernate.SQL=INFO
logging.level.org.hibernate.orm.jdbc.bind=OFF

# === Messages ===
spring.messages.basename=messages

# === Flyway ===
logging.level.org.flywaydb=INFO
spring.flyway.enabled=true

# === OpenAPI ===
springdoc.api-docs.path=/v3/api-docs

# === Security ===
security.secret=${JWT_SECRET_KEY}
security.access-token.expiration=15m
security.refresh-token.expiration=7d
security.refresh-token.secure-cookie=true

# === Application Mail ===
app.mail.from=no-reply@merimna.local

# === Frontend ===
app.frontend.reset-password-url=http://localhost:5173/reset-password
