spring.application.name=merimna

# === Server Configuration ===
server.port=8080
server.servlet.context-path=/api

# === Database Connection ===
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

# === JPA / Hibernate Configuration ===
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# === Logging ===
logging.level.org.hibernate.SQL=DEBUG