/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getAllUsers"];
        put?: never;
        post: operations["create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/placements": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getAllPlacements"];
        put?: never;
        post: operations["create_1"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/placements/{placementPublicId}/terminate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["terminate"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/legal-representatives": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["createLegalRepresentative"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/house-units": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getAllHouseUnits"];
        put?: never;
        post: operations["createHouseUnit"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/employees": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getAllEmployees"];
        put?: never;
        post: operations["createEmployee"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/employees/{employeePublicId}/terminate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["terminateEmployee"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/employees/{employeePublicId}/reactivate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["reactivateEmployee"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/employees/{employeePublicId}/assignments": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getAllAssignments"];
        put?: never;
        post: operations["create_2"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/employees/{employeePublicId}/assignments/{assignmentPublicId}/terminate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["terminateAssignment"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/employees/{employeePublicId}/assignments/{assignmentPublicId}/cancel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["cancelAssignment"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/employee-positions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["create_3"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/beneficiaries": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get beneficiaries
         * @description Returns a paginated list of beneficiaries. When amka is provided, q is ignored.
         */
        get: operations["getBeneficiaries"];
        put?: never;
        /** Create beneficiary */
        post: operations["create_4"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/beneficiaries/{beneficiaryPublicId}/medications": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getMedications"];
        put?: never;
        post: operations["addMedication"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/beneficiaries/{beneficiaryPublicId}/legal-representatives/{legalRepresentativeId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["assignLegalRepresentative"];
        delete: operations["unassignLegalRepresentative"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/beneficiaries/{beneficiaryPublicId}/discharge": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Discharge beneficiary */
        post: operations["discharge"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/beneficiaries/{beneficiaryPublicId}/allergies": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getAllergiesByBeneficiary"];
        put?: never;
        post: operations["createAllergy"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/reset-password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["resetPassword"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["refresh"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["logout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/forgot-password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["forgotPassword"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users/{publicId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getUserByPublicId"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch: operations["updateUser"];
        trace?: never;
    };
    "/users/me/password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch: operations["changePassword"];
        trace?: never;
    };
    "/legal-representatives/{legalRepresentativeId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getLegalRepresentativeById"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch: operations["updateLegalRepresentative"];
        trace?: never;
    };
    "/house-units/{houseUnitPublicId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getHouseUnit"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch: operations["updateHouseUnit"];
        trace?: never;
    };
    "/employees/{employeePublicId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getEmployeeByPublicId"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch: operations["updateEmployee"];
        trace?: never;
    };
    "/beneficiaries/{beneficiaryPublicId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get beneficiary by ID */
        get: operations["getById"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update Beneficiary */
        patch: operations["updateBeneficiary"];
        trace?: never;
    };
    "/beneficiaries/{beneficiaryPublicId}/medications/{medicationPublicId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getMedicationByPublicId"];
        put?: never;
        post?: never;
        delete: operations["deleteMedication"];
        options?: never;
        head?: never;
        patch: operations["updateMedication"];
        trace?: never;
    };
    "/beneficiaries/{beneficiaryPublicId}/house-unit/{houseUnitPublicId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Change beneficiary house unit */
        patch: operations["changeHouseUnit"];
        trace?: never;
    };
    "/beneficiaries/{beneficiaryPublicId}/allergies/{allergyPublicId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getAllergyByPublicId"];
        put?: never;
        post?: never;
        delete: operations["deleteAllergy"];
        options?: never;
        head?: never;
        patch: operations["updateAllergy"];
        trace?: never;
    };
    "/users/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getCurrentUser"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/placements/{placementPublicId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getPlacement"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/employees/{employeePublicId}/assignments/{assignmentPublicId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getAssignmentByPublicId"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        UserCreateDTO: {
            /** Format: uuid */
            employeePublicId?: string;
            username?: string;
            email?: string;
            password?: string;
            /** @enum {string} */
            role?: "ADMIN" | "STAFF";
        };
        UserReadOnlyDTO: {
            /** Format: uuid */
            publicId?: string;
            username?: string;
            email?: string;
            /** @enum {string} */
            role?: "ADMIN" | "STAFF";
            active?: boolean;
        };
        /** @description Request payload for creating an employee placement. */
        EmployeePlacementCreateDTO: {
            /**
             * Format: uuid
             * @description Public identifier of the employee to be placed
             * @example 550e8400-e29b-41d4-a716-446655440000
             */
            employeePublicId?: string;
            /**
             * Format: uuid
             * @description Public identifier of the house unit
             * @example 550e8400-e29b-41d4-a716-446655440000
             */
            houseUnitPublicId?: string;
            /**
             * Format: date
             * @description Placement start date.
             * @example 2026-04-21
             */
            startDate?: string;
            /**
             * Format: date
             * @description Placement end date. Nullable for open-ended placement.
             * @example 2026-04-25
             */
            endDate?: string;
            /**
             * @description Reason for the placement.
             * @example TEMPORARY_COVERAGE
             * @enum {string}
             */
            reason?: "TEMPORARY_COVERAGE";
        };
        EmployeePlacementReadOnlyDTO: {
            /** Format: uuid */
            publicId?: string;
            houseUnitCode?: string;
            houseUnitDisplayName?: string;
            /** Format: date */
            startDate?: string;
            /** Format: date */
            endDate?: string;
            /** @enum {string} */
            reason?: "TEMPORARY_COVERAGE";
            active?: boolean;
        };
        /** @description Request payload for terminating an employee placement. */
        EmployeePlacementTerminateDTO: {
            /**
             * Format: date
             * @description End date of the placement
             * @example 2026-04-26
             */
            endDate?: string;
        };
        LegalRepresentativeCreateDTO: {
            afm?: string;
            /** @enum {string} */
            type?: "JUDICIAL_SUPPORTER" | "LEGAL_GUARDIAN" | "PUBLIC_AUTHORITY" | "OTHER";
            firstName?: string;
            lastName?: string;
            mobileNumber?: string;
            landlinePhone?: string;
            email?: string;
            notes?: string;
        };
        LegalRepresentativeReadOnlyDTO: {
            /** Format: int64 */
            id?: number;
            /** @enum {string} */
            type?: "JUDICIAL_SUPPORTER" | "LEGAL_GUARDIAN" | "PUBLIC_AUTHORITY" | "OTHER";
            firstName?: string;
            lastName?: string;
            mobileNumber?: string;
            landlinePhone?: string;
            email?: string;
            notes?: string;
        };
        HouseUnitCreateDTO: {
            code?: string;
            displayName?: string;
            address?: string;
            /** Format: int32 */
            maxCapacity?: number;
        };
        HouseUnitReadOnlyDTO: {
            /** Format: uuid */
            publicId?: string;
            code?: string;
            displayName?: string;
            address?: string;
            /** Format: int32 */
            maxCapacity?: number;
        };
        /** @description Address payload */
        AddressDTO: {
            /**
             * @description Street name
             * @example Ηρώων & Τσαλδάρη
             */
            street?: string;
            /**
             * @description Street number
             * @example 12Α
             */
            streetNumber?: string;
            /**
             * @description City name
             * @example Αθήνα
             */
            city?: string;
            /**
             * @description Postal code
             * @example 10431
             */
            zipCode?: string;
        };
        EmployeeCreateDTO: {
            /**
             * @description Employee first name
             * @example Γεώργιος
             */
            firstName?: string;
            /**
             * @description Employee last name
             * @example Παπαδόπουλος
             */
            lastName?: string;
            /**
             * @description Employee email address
             * @example g.papadopoulos@merimna.gr
             */
            contactEmail?: string;
            /**
             * @description Employee mobile number
             * @example +306942318223
             */
            mobileNumber?: string;
            /** @description Employee residential address */
            address?: components["schemas"]["AddressDTO"];
            /**
             * @description Employee position code
             * @example CAREGIVER
             */
            positionCode?: string;
            /**
             * Format: date
             * @description Employee hire date
             * @example 2026-02-23
             */
            hireDate?: string;
        };
        EmployeeAssignmentReadOnlyDTO: {
            /** Format: uuid */
            publicId?: string;
            /** Format: uuid */
            houseUnitPublicId?: string;
            houseUnitDisplayName?: string;
            /** @enum {string} */
            status?: "ACTIVE" | "CANCELLED" | "TERMINATED" | "COMPLETED";
            /** Format: date */
            startDate?: string;
            /** Format: date */
            endDate?: string;
        };
        EmployeeDetailsDTO: {
            /**
             * Format: uuid
             * @description Public identifier of the employee
             * @example 550e8400-e29b-41d4-a716-446655440000
             */
            publicId: string;
            /**
             * @description Employee first name
             * @example Γεώργιος
             */
            firstName: string;
            /**
             * @description Employee last name
             * @example Παπαδόπουλος
             */
            lastName: string;
            /**
             * @description Employee email address
             * @example g.papadopoulos@merimna.gr
             */
            contactEmail: string;
            /**
             * @description Employee mobile number
             * @example +306942318223
             */
            mobileNumber: string;
            /**
             * @description Employee position code
             * @example CAREGIVER
             */
            positionCode: string;
            /**
             * @description Employee position display name
             * @example Caregiver
             */
            positionDisplayName: string;
            /**
             * @description House unit assignments for this employee
             * @example [
             *       {
             *         "houseUnitCode": "UNIT_A",
             *         "status": "ACTIVE"
             *       }
             *     ]
             */
            assignments: components["schemas"]["EmployeeAssignmentReadOnlyDTO"][];
            /** @description Optional active placement. Null when the employee has no active placement. */
            activePlacement?: components["schemas"]["EmployeePlacementReadOnlyDTO"];
            /**
             * Format: date
             * @description Employee hire date
             * @example 2026-02-23
             */
            hireDate: string;
            /** @description Employee residential address */
            address: components["schemas"]["AddressDTO"];
            /**
             * @description Indicates whether the employee is active
             * @example true
             */
            active: boolean;
        };
        /** @description Request payload for terminating an employee */
        EmployeeTerminateDTO: {
            /**
             * Format: date
             * @description Employee termination date
             * @example 2026-04-11
             */
            terminationDate: string;
        };
        EmployeeAssignmentCreateDTO: {
            /** Format: uuid */
            houseUnitPublicId?: string;
            /** Format: date */
            startDate?: string;
            /** Format: date */
            endDate?: string;
        };
        /** @description Request payload for creating an employee position. */
        EmployeePositionCreateDTO: {
            /**
             * @description Unique employee position code.
             * @example CAREGIVER
             */
            code?: string;
            /**
             * @description Human-readable employee position name.
             * @example Caregiver
             */
            displayName?: string;
            /**
             * @description Whether employees in this position require exclusive placement.
             * @example false
             */
            requiresExclusivePlacement?: boolean;
            /** @description Permissions granted to this employee position. */
            permissions?: ("BENEFICIARY_READ" | "BENEFICIARY_CREATE" | "BENEFICIARY_UPDATE" | "BENEFICIARY_DISCHARGE" | "EMPLOYEE_READ" | "EMPLOYEE_CREATE" | "EMPLOYEE_UPDATE" | "EMPLOYEE_TERMINATE" | "EMPLOYEE_REACTIVATE" | "HOUSE_UNIT_READ" | "HOUSE_UNIT_CREATE" | "HOUSE_UNIT_UPDATE" | "ASSIGNMENT_READ" | "ASSIGNMENT_CREATE" | "ASSIGNMENT_TERMINATE" | "ASSIGNMENT_CANCEL" | "USER_READ" | "USER_CREATE" | "USER_UPDATE" | "USER_DEACTIVATE" | "USER_REACTIVATE" | "PLACEMENT_READ" | "PLACEMENT_CREATE" | "PLACEMENT_UPDATE" | "PLACEMENT_TERMINATE")[];
        };
        EmployeePositionReadOnlyDTO: {
            code?: string;
            displayName?: string;
            requiresExclusivePlacement?: boolean;
            permissions?: ("BENEFICIARY_READ" | "BENEFICIARY_CREATE" | "BENEFICIARY_UPDATE" | "BENEFICIARY_DISCHARGE" | "EMPLOYEE_READ" | "EMPLOYEE_CREATE" | "EMPLOYEE_UPDATE" | "EMPLOYEE_TERMINATE" | "EMPLOYEE_REACTIVATE" | "HOUSE_UNIT_READ" | "HOUSE_UNIT_CREATE" | "HOUSE_UNIT_UPDATE" | "ASSIGNMENT_READ" | "ASSIGNMENT_CREATE" | "ASSIGNMENT_TERMINATE" | "ASSIGNMENT_CANCEL" | "USER_READ" | "USER_CREATE" | "USER_UPDATE" | "USER_DEACTIVATE" | "USER_REACTIVATE" | "PLACEMENT_READ" | "PLACEMENT_CREATE" | "PLACEMENT_UPDATE" | "PLACEMENT_TERMINATE")[];
        };
        BeneficiaryCreateDTO: {
            /**
             * @description First name of the beneficiary
             * @example Γεώργιος
             */
            firstName?: string;
            /**
             * @description Last name of the beneficiary
             * @example Παπαδόπουλος
             */
            lastName?: string;
            /**
             * @description 11-digit Greek social security number (AMKA)
             * @example 12345678901
             */
            amka?: string;
            /**
             * Format: date
             * @description Date of birth (must be in the past)
             * @example 1965-04-23
             */
            dateOfBirth?: string;
            /**
             * Format: uuid
             * @description Public identifier of the house unit the beneficiary is assigned to
             * @example 550e8400-e29b-41d4-a716-446655440000
             */
            houseUnitPublicId?: string;
            /** @description Permanent residential address of the beneficiary */
            permanentAddress?: components["schemas"]["AddressDTO"];
            /** @description Emergency contact person for the beneficiary */
            emergencyContact?: components["schemas"]["EmergencyContactDTO"];
        };
        /** @description Emergency contact person for the beneficiary. At least one phone number is required. */
        EmergencyContactDTO: {
            /**
             * @description First name of the emergency contact
             * @example Μαρία
             */
            firstName?: string;
            /**
             * @description Last name of the emergency contact
             * @example Παπαδοπούλου
             */
            lastName?: string;
            /**
             * @description Relationship to the beneficiary
             * @example CHILD
             * @enum {string}
             */
            relationshipType?: "PARENT" | "SIBLING" | "OTHER_RELATIVE" | "FRIEND" | "SOCIAL_WORKER" | "OTHER";
            /**
             * @description Landline phone number
             * @example 2101234567
             */
            landlinePhone?: string;
            /**
             * @description Mobile phone number
             * @example 6971234567
             */
            mobileNumber?: string;
            /**
             * @description Email address of the emergency contact
             * @example maria@example.com
             */
            email?: string;
            /** @description Residential address of the emergency contact */
            address?: components["schemas"]["AddressDTO"];
        };
        ValidationErrorResponse: {
            /** @example VALIDATION_FAILED */
            type?: string;
            /** @example Bad Request */
            title?: string;
            /**
             * Format: int32
             * @example 400
             */
            status?: number;
            /** @example Παρουσιάστηκαν σφάλματα κατά την επικύρωση των στοιχείων. */
            detail?: string;
            /**
             * @description Field validation errors
             * @example {
             *       "firstName": [
             *         "Το όνομα μπορεί να περιέχει μόνο ελληνικούς ή λατινικούς χαρακτήρες.",
             *         "Το όνομα πρέπει να αποτελείται από 3 έως 20 χαρακτήρες."
             *       ]
             *     }
             */
            validationErrors?: {
                [key: string]: string[];
            };
            /** @example /api/beneficiaries */
            path?: string;
            /** @example 2026-03-20T11:33:15 */
            timestamp?: string;
        };
        ConflictErrorResponse: {
            /** @example CONFLICT_ERROR */
            type?: string;
            /** @example Conflict */
            title?: string;
            /**
             * Format: int32
             * @example 409
             */
            status?: number;
            /** @example Resource conflict */
            detail?: string;
            /** @example /api/beneficiaries */
            path?: string;
            /** @example 2026-03-20T11:33:15 */
            timestamp?: string;
        };
        AllergyReadOnlyDTO: {
            /** Format: uuid */
            publicId?: string;
            substance?: string;
            /** @enum {string} */
            severity?: "LOW" | "MEDIUM" | "HIGH";
            reaction?: string;
        };
        BeneficiaryDetailsDTO: {
            /**
             * Format: uuid
             * @description Public identifier of the beneficiary
             * @example 550e8400-e29b-41d4-a716-446655440000
             */
            publicId?: string;
            /**
             * @description First name
             * @example Γεώργιος
             */
            firstName?: string;
            /**
             * @description Last name
             * @example Παπαδόπουλος
             */
            lastName?: string;
            /**
             * @description 11-digit Greek social security number (AMKA)
             * @example 12345678901
             */
            amka?: string;
            /**
             * Format: date
             * @description Date of birth
             * @example 1965-04-23
             */
            dateOfBirth?: string;
            /**
             * @description Whether the beneficiary is currently active
             * @example true
             */
            isActive?: boolean;
            /**
             * Format: date
             * @description Official discharge date. Null while the beneficiary is active.
             * @example 2026-05-03
             */
            dischargeDate?: string;
            /**
             * @description Reason for discharging the beneficiary. Null while the beneficiary is active.
             * @example Completion of supported living services.
             */
            dischargeReason?: string;
            /**
             * Format: uuid
             * @description Public identifier of the employee who recorded the discharge. Null while the beneficiary is active.
             * @example 7b9f0e0a-6e1a-4e8c-9f61-5f5f2f7f5d3a
             */
            dischargedByEmployeePublicId?: string;
            /**
             * @description Full name of the employee who recorded the discharge. Null while the beneficiary is active.
             * @example John Doe
             */
            dischargedByEmployeeFullName?: string;
            /**
             * Format: uuid
             * @description Public identifier of the assigned house unit
             * @example 7d3a4b9e-4e78-4e9d-8a2d-21dcbf4a7f10
             */
            houseUnitPublicId?: string;
            /**
             * @description Assigned house unit code
             * @example UNIT_A
             */
            houseUnitCode?: string;
            /**
             * @description Assigned house unit display name
             * @example ΣΥΔ 2
             */
            houseUnitDisplayName?: string;
            /** @description Permanent residential address */
            permanentAddress?: components["schemas"]["AddressDTO"];
            /** @description Emergency contact person */
            emergencyContact?: components["schemas"]["EmergencyContactDTO"];
            /** @description Current medications of the beneficiary */
            medications?: components["schemas"]["MedicationReadOnlyDTO"][];
            /** @description Known allergies of the beneficiary */
            allergies?: components["schemas"]["AllergyReadOnlyDTO"][];
            /** @description Legal representatives of the beneficiary */
            legalRepresentatives?: components["schemas"]["LegalRepresentativeReadOnlyDTO"][];
        };
        MedicationReadOnlyDTO: {
            /** Format: uuid */
            publicId?: string;
            name?: string;
            dosage?: string;
            frequency?: string;
            administrationTimes?: string;
            instructions?: string;
        };
        MedicationCreateDTO: {
            name?: string;
            dosage?: string;
            frequency?: string;
            administrationTimes?: string;
            instructions?: string;
        };
        /** @description Request body used to discharge a beneficiary from active support. */
        DischargeRequestDTO: {
            /**
             * Format: date
             * @description Official discharge date. Must be today or a past date; future discharge scheduling is not supported in V1.
             * @example 2026-05-03
             */
            dischargeDate: string;
            /**
             * @description Reason for discharging the beneficiary. Stored as free text in V1.
             * @example Completion of supported living services.
             */
            dischargeReason: string;
        };
        NotFoundErrorResponse: {
            /** @example ENTITY_NOT_FOUND */
            type?: string;
            /** @example Not Found */
            title?: string;
            /**
             * Format: int32
             * @example 404
             */
            status?: number;
            /** @example The requested resource was not found */
            detail?: string;
            /** @example /api/beneficiaries/1 */
            path?: string;
            /** @example 2026-03-20T11:33:15 */
            timestamp?: string;
        };
        AllergyCreateDTO: {
            substance?: string;
            /** @enum {string} */
            severity?: "LOW" | "MEDIUM" | "HIGH";
            reaction?: string;
        };
        ResetPasswordRequest: {
            /**
             * @description Raw password reset token received from the password reset link.
             * @example A8xQmZ0pY2N4Q3VwU2VjdXJlUmVzZXRUb2tlbg
             */
            token?: string;
            /**
             * @description New password for the account.
             * @example NewStrongPassword123!
             */
            newPassword?: string;
        };
        RefreshRequest: {
            /** @description Opaque refresh token issued at login */
            refreshToken: string;
        };
        AuthResponse: {
            /** @description Short-lived JWT access token */
            accessToken: string;
            /** @description Long-lived opaque refresh token */
            refreshToken: string;
        };
        LoginRequest: {
            /**
             * @description Email address of the user
             * @example admin@merimna.local
             */
            email?: string;
            /**
             * @description Password of the user
             * @example password123
             */
            password?: string;
        };
        ForgotPasswordRequest: {
            /**
             * @description Email address of the account requesting a password reset.
             * @example user@example.com
             */
            email?: string;
        };
        UserUpdateDTO: {
            /**
             * @description User email address
             * @example g.papadopoulos@merimna.gr
             */
            email?: string;
        };
        ChangePasswordDTO: {
            currentPassword?: string;
            newPassword?: string;
        };
        LegalRepresentativeUpdateDTO: {
            /** @enum {string} */
            type?: "JUDICIAL_SUPPORTER" | "LEGAL_GUARDIAN" | "PUBLIC_AUTHORITY" | "OTHER";
            afm?: string;
            firstName?: string;
            lastName?: string;
            mobileNumber?: string;
            landlinePhone?: string;
            email?: string;
            notes?: string;
        };
        HouseUnitUpdateDTO: {
            code?: string;
            displayName?: string;
            address?: string;
            /** Format: int32 */
            maxCapacity?: number;
        };
        /** @description Partial address update payload */
        AddressUpdateDTO: {
            /**
             * @description Street name. Optional in PATCH requests.
             * @example Ηρώων & Τσαλδάρη
             */
            street?: string;
            /**
             * @description Street number. Optional in PATCH requests.
             * @example 12Α
             */
            streetNumber?: string;
            /**
             * @description City name. Optional in PATCH requests.
             * @example Αθήνα
             */
            city?: string;
            /**
             * @description Postal code. Optional in PATCH requests.
             * @example 10431
             */
            zipCode?: string;
        };
        EmployeeUpdateDTO: {
            /**
             * @description Employee first name
             * @example Γεώργιος
             */
            firstName?: string;
            /**
             * @description Employee last name
             * @example Παπαδόπουλος
             */
            lastName?: string;
            /**
             * @description Employee email address
             * @example g.papadopoulos@merimna.gr
             */
            contactEmail?: string;
            /**
             * @description Employee mobile number
             * @example +306942318223
             */
            mobileNumber?: string;
            /**
             * @description Employee position code
             * @example CAREGIVER
             */
            positionCode?: string;
            /**
             * Format: date
             * @description Employee hire date
             * @example 2026-02-23
             */
            hireDate?: string;
            /** @description Employee residential address */
            address?: components["schemas"]["AddressUpdateDTO"];
        };
        BeneficiaryUpdateDTO: {
            /**
             * @description Updated first name
             * @example Γεώργιος
             */
            firstName?: string;
            /**
             * @description Updated last name
             * @example Παπαδόπουλος
             */
            lastName?: string;
            /**
             * @description Updated AMKA — 11-digit Greek social security number
             * @example 12345678901
             */
            amka?: string;
            /**
             * Format: date
             * @description Updated date of birth
             * @example 1965-04-23
             */
            dateOfBirth?: string;
            /** @description Updated permanent address. Only provided fields will be changed. */
            permanentAddress?: components["schemas"]["AddressUpdateDTO"];
            /** @description Updated emergency contact. Only provided fields will be changed. */
            emergencyContact?: components["schemas"]["EmergencyContactUpdateDTO"];
        };
        EmergencyContactUpdateDTO: {
            firstName?: string;
            lastName?: string;
            /** @enum {string} */
            relationshipType?: "PARENT" | "SIBLING" | "OTHER_RELATIVE" | "FRIEND" | "SOCIAL_WORKER" | "OTHER";
            landlinePhone?: string;
            mobileNumber?: string;
            email?: string;
            address?: components["schemas"]["AddressUpdateDTO"];
        };
        MedicationUpdateDTO: {
            name?: string;
            dosage?: string;
            frequency?: string;
            administrationTimes?: string;
            instructions?: string;
        };
        BeneficiaryListDTO: {
            /**
             * Format: uuid
             * @description Public identifier of the beneficiary
             * @example 550e8400-e29b-41d4-a716-446655440000
             */
            publicId?: string;
            /**
             * @description First name
             * @example Γεώργιος
             */
            firstName?: string;
            /**
             * @description Last name
             * @example Παπαδόπουλος
             */
            lastName?: string;
            /**
             * Format: uuid
             * @description Public identifier of the assigned house unit
             * @example 7d3a4b9e-4e78-4e9d-8a2d-21dcbf4a7f10
             */
            houseUnitPublicId?: string;
            /**
             * @description Code of the assigned house unit
             * @example UNIT_A
             */
            houseUnitCode?: string;
            /**
             * @description Display name of the assigned house unit
             * @example House Unit A
             */
            houseUnitDisplayName?: string;
            /**
             * @description Whether the beneficiary is currently active
             * @example true
             */
            isActive?: boolean;
        };
        AllergyUpdateDTO: {
            /** Format: uuid */
            publicId?: string;
            substance?: string;
            /** @enum {string} */
            severity?: "LOW" | "MEDIUM" | "HIGH";
            reaction?: string;
        };
        /** @description Search filters for users */
        UserSearchDTO: {
            /**
             * @description Search term. Applies to username and email, case-insensitive.
             * @example john
             */
            q?: string;
            /**
             * @description Filter by user role
             * @example ADMIN
             * @enum {string}
             */
            role?: "ADMIN" | "STAFF";
            /**
             * @description Include inactive users in results
             * @default false
             * @example false
             */
            includeInactive: boolean;
        };
        Pageable: {
            /** Format: int32 */
            page?: number;
            /** Format: int32 */
            size?: number;
            sort?: string[];
        };
        PageResponseUserReadOnlyDTO: {
            content?: components["schemas"]["UserReadOnlyDTO"][];
            /** Format: int32 */
            page?: number;
            /** Format: int32 */
            size?: number;
            /** Format: int64 */
            totalElements?: number;
            /** Format: int32 */
            totalPages?: number;
        };
        DateRange: {
            /** Format: date */
            from?: string;
            /** Format: date */
            to?: string;
        };
        /** @description Search filters for employee placements. All fields are optional. */
        EmployeePlacementSearchDTO: {
            /**
             * Format: uuid
             * @description Filter by employee public identifier.
             * @example 550e8400-e29b-41d4-a716-446655440000
             */
            employeePublicId?: string;
            /**
             * Format: uuid
             * @description Filter by house unit public identifier, usually selected from a UI dropdown.
             * @example 550e8400-e29b-41d4-a716-446655440000
             */
            houseUnitPublicId?: string;
            /**
             * @description Whether inactive placements should be included in the results.
             * @example false
             */
            includeInactive?: boolean;
            /** @description Filter by placement start date range. */
            startDateRange?: components["schemas"]["DateRange"];
            /** @description Filter by placement end date range. */
            endDateRange?: components["schemas"]["DateRange"];
        };
        PageResponseEmployeePlacementReadOnlyDTO: {
            content?: components["schemas"]["EmployeePlacementReadOnlyDTO"][];
            /** Format: int32 */
            page?: number;
            /** Format: int32 */
            size?: number;
            /** Format: int64 */
            totalElements?: number;
            /** Format: int32 */
            totalPages?: number;
        };
        /** @description Search filters for employees. All fields are optional. */
        EmployeeSearchDTO: {
            /**
             * @description Free-text search (first name, last name, email)
             * @example giannis
             */
            q?: string;
            /**
             * @description Employee position code
             * @example CAREGIVER
             */
            positionCode?: string;
            /**
             * Format: uuid
             * @description Filter by assigned house unit public identifier, usually selected from a UI dropdown.
             * @example 550e8400-e29b-41d4-a716-446655440000
             */
            houseUnitPublicId?: string;
            /**
             * @description Filter by employee status
             * @example ACTIVE
             * @enum {string}
             */
            status?: "ALL" | "ACTIVE" | "INACTIVE";
        };
        EmployeeListDTO: {
            /**
             * Format: uuid
             * @description Public identifier of the employee
             * @example 550e8400-e29b-41d4-a716-446655440000
             */
            publicId: string;
            /**
             * @description First name
             * @example Giannis
             */
            firstName: string;
            /**
             * @description Last name
             * @example Papadopoulos
             */
            lastName: string;
            /**
             * @description Employee position code
             * @example CAREGIVER
             */
            positionCode: string;
            /**
             * @description Employee position display name
             * @example Caregiver
             */
            positionDisplayName: string;
            /**
             * @description Indicates whether the employee is active
             * @example true
             */
            active: boolean;
        };
        PageResponseEmployeeListDTO: {
            content?: components["schemas"]["EmployeeListDTO"][];
            /** Format: int32 */
            page?: number;
            /** Format: int32 */
            size?: number;
            /** Format: int64 */
            totalElements?: number;
            /** Format: int32 */
            totalPages?: number;
        };
        BeneficiarySearchDTO: {
            /**
             * @description Global search term (firstName, lastName, AMKA partial match). Ignored if amka is provided.
             * @example Παπαδόπουλος
             */
            q?: string;
            /**
             * @description Exact AMKA lookup. When present, q is ignored.
             * @example 12345678901
             */
            amka?: string;
            /**
             * @description Include inactive beneficiaries in results. Defaults to false.
             * @example false
             */
            includeInactive?: boolean;
            /**
             * Format: uuid
             * @description Filter by house unit public identifier, usually selected from a UI dropdown.
             * @example 550e8400-e29b-41d4-a716-446655440000
             */
            houseUnitPublicId?: string;
        };
        PageResponseBeneficiaryListDTO: {
            content?: components["schemas"]["BeneficiaryListDTO"][];
            /** Format: int32 */
            page?: number;
            /** Format: int32 */
            size?: number;
            /** Format: int64 */
            totalElements?: number;
            /** Format: int32 */
            totalPages?: number;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getAllUsers: {
        parameters: {
            query: {
                criteria: components["schemas"]["UserSearchDTO"];
                pageable: components["schemas"]["Pageable"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["PageResponseUserReadOnlyDTO"];
                };
            };
        };
    };
    create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UserCreateDTO"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["UserReadOnlyDTO"];
                };
            };
        };
    };
    getAllPlacements: {
        parameters: {
            query: {
                criteria: components["schemas"]["EmployeePlacementSearchDTO"];
                pageable: components["schemas"]["Pageable"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["PageResponseEmployeePlacementReadOnlyDTO"];
                };
            };
        };
    };
    create_1: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EmployeePlacementCreateDTO"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["EmployeePlacementReadOnlyDTO"];
                };
            };
        };
    };
    terminate: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                placementPublicId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EmployeePlacementTerminateDTO"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    createLegalRepresentative: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LegalRepresentativeCreateDTO"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["LegalRepresentativeReadOnlyDTO"];
                };
            };
        };
    };
    getAllHouseUnits: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["HouseUnitReadOnlyDTO"][];
                };
            };
        };
    };
    createHouseUnit: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["HouseUnitCreateDTO"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["HouseUnitReadOnlyDTO"];
                };
            };
        };
    };
    getAllEmployees: {
        parameters: {
            query: {
                criteria: components["schemas"]["EmployeeSearchDTO"];
                /** @description Zero-based page index (0..N) */
                page?: number;
                /** @description The size of the page to be returned */
                size?: number;
                /** @description Sorting criteria in the format: property,(asc|desc). Default sort order is ascending. Multiple sort criteria are supported. */
                sort?: string[];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["PageResponseEmployeeListDTO"];
                };
            };
        };
    };
    createEmployee: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EmployeeCreateDTO"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["EmployeeDetailsDTO"];
                };
            };
        };
    };
    terminateEmployee: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                employeePublicId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EmployeeTerminateDTO"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["EmployeeDetailsDTO"];
                };
            };
        };
    };
    reactivateEmployee: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                employeePublicId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["EmployeeDetailsDTO"];
                };
            };
        };
    };
    getAllAssignments: {
        parameters: {
            query?: {
                view?: "ACTIVE" | "PAST" | "ALL";
            };
            header?: never;
            path: {
                employeePublicId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["EmployeeAssignmentReadOnlyDTO"][];
                };
            };
        };
    };
    create_2: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                employeePublicId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EmployeeAssignmentCreateDTO"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["EmployeeAssignmentReadOnlyDTO"];
                };
            };
        };
    };
    terminateAssignment: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                employeePublicId: string;
                assignmentPublicId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    cancelAssignment: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                employeePublicId: string;
                assignmentPublicId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    create_3: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EmployeePositionCreateDTO"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["EmployeePositionReadOnlyDTO"];
                };
            };
        };
    };
    getBeneficiaries: {
        parameters: {
            query: {
                criteria: components["schemas"]["BeneficiarySearchDTO"];
                /** @description Zero-based page index (0..N) */
                page?: number;
                /** @description The size of the page to be returned */
                size?: number;
                /** @description Sorting criteria in the format: property,(asc|desc). Default sort order is ascending. Multiple sort criteria are supported. */
                sort?: string[];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["PageResponseBeneficiaryListDTO"];
                };
            };
            /** @description Validation error */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ValidationErrorResponse"];
                };
            };
        };
    };
    create_4: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BeneficiaryCreateDTO"];
            };
        };
        responses: {
            /** @description Beneficiary created successfully */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["BeneficiaryDetailsDTO"];
                };
            };
            /** @description Validation error */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ValidationErrorResponse"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConflictErrorResponse"];
                };
            };
        };
    };
    getMedications: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                beneficiaryPublicId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["MedicationReadOnlyDTO"][];
                };
            };
        };
    };
    addMedication: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                beneficiaryPublicId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MedicationCreateDTO"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["MedicationReadOnlyDTO"];
                };
            };
        };
    };
    assignLegalRepresentative: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                beneficiaryPublicId: string;
                legalRepresentativeId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    unassignLegalRepresentative: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                beneficiaryPublicId: string;
                legalRepresentativeId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    discharge: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /**
                 * @description Beneficiary public identifier
                 * @example 550e8400-e29b-41d4-a716-446655440000
                 */
                beneficiaryPublicId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DischargeRequestDTO"];
            };
        };
        responses: {
            /** @description Beneficiary discharged successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["BeneficiaryDetailsDTO"];
                };
            };
            /** @description Beneficiary not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NotFoundErrorResponse"];
                };
            };
            /** @description Beneficiary already inactive */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConflictErrorResponse"];
                };
            };
        };
    };
    getAllergiesByBeneficiary: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                beneficiaryPublicId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["AllergyReadOnlyDTO"][];
                };
            };
        };
    };
    createAllergy: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                beneficiaryPublicId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AllergyCreateDTO"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["AllergyReadOnlyDTO"];
                };
            };
        };
    };
    resetPassword: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ResetPasswordRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    refresh: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["RefreshRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["AuthResponse"];
                };
            };
        };
    };
    logout: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["RefreshRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["AuthResponse"];
                };
            };
        };
    };
    forgotPassword: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ForgotPasswordRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    getUserByPublicId: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                publicId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["UserReadOnlyDTO"];
                };
            };
        };
    };
    updateUser: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                publicId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UserUpdateDTO"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["UserReadOnlyDTO"];
                };
            };
        };
    };
    changePassword: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChangePasswordDTO"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    getLegalRepresentativeById: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                legalRepresentativeId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["LegalRepresentativeReadOnlyDTO"];
                };
            };
        };
    };
    updateLegalRepresentative: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                legalRepresentativeId: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LegalRepresentativeUpdateDTO"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["LegalRepresentativeReadOnlyDTO"];
                };
            };
        };
    };
    getHouseUnit: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                houseUnitPublicId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["HouseUnitReadOnlyDTO"];
                };
            };
        };
    };
    updateHouseUnit: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                houseUnitPublicId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["HouseUnitUpdateDTO"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["HouseUnitReadOnlyDTO"];
                };
            };
        };
    };
    getEmployeeByPublicId: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                employeePublicId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["EmployeeDetailsDTO"];
                };
            };
        };
    };
    updateEmployee: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                employeePublicId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EmployeeUpdateDTO"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["EmployeeDetailsDTO"];
                };
            };
        };
    };
    getById: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /**
                 * @description Beneficiary public identifier
                 * @example 550e8400-e29b-41d4-a716-446655440000
                 */
                beneficiaryPublicId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Beneficiary found successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["BeneficiaryDetailsDTO"];
                };
            };
            /** @description Beneficiary not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NotFoundErrorResponse"];
                };
            };
        };
    };
    updateBeneficiary: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /**
                 * @description Beneficiary public identifier
                 * @example 550e8400-e29b-41d4-a716-446655440000
                 */
                beneficiaryPublicId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BeneficiaryUpdateDTO"];
            };
        };
        responses: {
            /** @description Beneficiary updated successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["BeneficiaryDetailsDTO"];
                };
            };
            /** @description Validation error */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ValidationErrorResponse"];
                };
            };
            /** @description Beneficiary not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NotFoundErrorResponse"];
                };
            };
        };
    };
    getMedicationByPublicId: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                beneficiaryPublicId: string;
                medicationPublicId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["MedicationReadOnlyDTO"];
                };
            };
        };
    };
    deleteMedication: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                beneficiaryPublicId: string;
                medicationPublicId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    updateMedication: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                beneficiaryPublicId: string;
                medicationPublicId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MedicationUpdateDTO"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["MedicationReadOnlyDTO"];
                };
            };
        };
    };
    changeHouseUnit: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /**
                 * @description Beneficiary public identifier
                 * @example 550e8400-e29b-41d4-a716-446655440000
                 */
                beneficiaryPublicId: string;
                /**
                 * @description House unit public identifier
                 * @example 550e8400-e29b-41d4-a716-446655440000
                 */
                houseUnitPublicId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["BeneficiaryListDTO"];
                };
            };
            /** @description Validation error */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ValidationErrorResponse"];
                };
            };
            /** @description Beneficiary or house unit not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NotFoundErrorResponse"];
                };
            };
        };
    };
    getAllergyByPublicId: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                beneficiaryPublicId: string;
                allergyPublicId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["AllergyReadOnlyDTO"];
                };
            };
        };
    };
    deleteAllergy: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                beneficiaryPublicId: string;
                allergyPublicId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    updateAllergy: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                beneficiaryPublicId: string;
                allergyPublicId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AllergyUpdateDTO"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["AllergyReadOnlyDTO"];
                };
            };
        };
    };
    getCurrentUser: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["UserReadOnlyDTO"];
                };
            };
        };
    };
    getPlacement: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                placementPublicId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["EmployeePlacementReadOnlyDTO"];
                };
            };
        };
    };
    getAssignmentByPublicId: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                employeePublicId: string;
                assignmentPublicId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["EmployeeAssignmentReadOnlyDTO"];
                };
            };
        };
    };
}
