create table user_invitations
(
    id          bigint generated by default as identity primary key,
    version     bigint      not null default 0,
    token_hash  varchar(64) not null,
    employee_id bigint      not null,
    created_at  timestamptz not null,
    expires_at  timestamptz not null,
    accepted_at timestamptz,
    revoked_at  timestamptz,

    constraint uk_user_invitations_token_hash unique (token_hash),

    constraint fk_user_invitations_employee
        foreign key (employee_id) references employees (id)
);

create index idx_user_invitations_employee_id
    on user_invitations (employee_id);