package io.github.amichailides.merimna.domain;

public enum Permission {

    BENEFICIARY_READ,
    BENEFICIARY_CREATE,
    BENEFICIARY_UPDATE,
    BENEFICIARY_DISCHARGE,

    EMPLOYEE_READ,
    EMPLOYEE_CREATE,
    EMPLOYEE_UPDATE,
    EMPLOYEE_TERMINATE,
    EMPLOYEE_REACTIVATE,

    HOUSE_UNIT_READ,
    HOUSE_UNIT_CREATE,
    HOUSE_UNIT_UPDATE,

    ASSIGNMENT_READ,
    ASSIGNMENT_CREATE,
    ASSIGNMENT_TERMINATE,
    ASSIGNMENT_CANCEL,

    USER_CREATE
}
