CREATE EXTENSION IF NOT EXISTS unaccent;

create table house_units
(
    id           bigint generated by default as identity primary key,
    code         varchar(20)  not null,
    display_name varchar(255) not null,
    address      varchar(255) not null,
    max_capacity INTEGER      NOT NULL,

    constraint uk_house_units_code UNIQUE (code)
);

create table beneficiaries
(
    -- PK
    id                       bigint generated by default as identity primary key,

    -- Core identity
    first_name               varchar(255) not null,
    last_name                varchar(255) not null,
    amka                     varchar(11)  not null,
    date_of_birth            date         not null,

    -- Status / classification
    is_active                boolean      not null,
    -- TODO(#3): Replace CHECK with PostgreSQL ENUM when domain values stabilize.
    house_unit_id            bigint       not null,

    -- Permanent address
    perm_street              varchar(255) not null,
    perm_street_number       varchar(255) not null,
    perm_city                varchar(255) not null,
    perm_zip_code            varchar(255) not null,

    -- Emergency contact
    emergency_first_name     varchar(255) not null,
    emergency_last_name      varchar(255) not null,
    emergency_relationship   varchar(255) not null
        constraint chk_beneficiaries_emergency_relationship
            check ((emergency_relationship)::text = any
                   ((array [
                       'PARENT'::character varying,
                       'SIBLING'::character varying,
                       'OTHER_RELATIVE'::character varying,
                       'FRIEND'::character varying,
                       'SOCIAL_WORKER'::character varying,
                       'OTHER'::character varying
                       ])::text[])),
    emergency_mobile_number  varchar(255),
    emergency_landline_phone varchar(255),
    emergency_email          varchar(255),
    emergency_street         varchar(255) not null,
    emergency_street_number  varchar(255),
    emergency_city           varchar(255) not null,
    emergency_zip_code       varchar(255) not null,

    constraint uk_beneficiaries_amka unique (amka),
    constraint fk_beneficiaries_house_unit FOREIGN KEY (house_unit_id) REFERENCES house_units (id)
);

create table allergies
(
    beneficiary_id bigint       not null
        constraint fk_allergies_beneficiary
            references beneficiaries (id) on delete cascade,
    id             bigint generated by default as identity
        primary key,
    reaction       varchar(255) not null,
    severity       varchar(255) not null
        constraint chk_allergies_severity
            check ((severity)::text = ANY
                   ((ARRAY [
                       'LOW':: character varying,
                       'MEDIUM':: character varying,
                       'HIGH':: character varying
                       ])::text[])
                ),
    substance      varchar(255) not null
);

create table medications
(
    beneficiary_id       bigint       not null
        constraint fk_medication_beneficiary
            references beneficiaries (id) on delete cascade,
    id                   bigint generated by default as identity
        primary key,
    administration_times varchar(255) not null,
    dosage               varchar(255) not null,
    frequency            varchar(255) not null,
    instructions         varchar(255),
    name                 varchar(255) not null
);

create table legal_representatives
(
    id             bigint generated by default as identity primary key,
    afm            varchar(11)  not null
        constraint uk_legal_representatives_afm unique,
    type           varchar(255) not null
        constraint chk_legal_representatives_type
            check ((type)::text = ANY
                   ((ARRAY [
                       'JUDICIAL_SUPPORTER':: character varying,
                       'LEGAL_GUARDIAN':: character varying,
                       'PUBLIC_AUTHORITY':: character varying,
                       'OTHER':: character varying
                       ])::text[])
                ),
    first_name     varchar(255) not null,
    last_name      varchar(255) not null,
    mobile_number  varchar(20),
    landline_phone varchar(20),
    email          varchar(255)
        constraint uk_legal_representatives_email unique,
    notes          text
);

create table beneficiary_legal_representatives
(
    beneficiary_id          bigint not null,
    legal_representative_id bigint not null,

    constraint pk_beneficiary_legal_representatives
        primary key (beneficiary_id, legal_representative_id),

    constraint fk_beneficiary_legal_representatives_beneficiary
        foreign key (beneficiary_id)
            references beneficiaries (id)
            on delete cascade,

    constraint fk_beneficiary_legal_representatives_legal_representative
        foreign key (legal_representative_id)
            references legal_representatives (id)
            on delete cascade
);

create table roles
(
    id   bigint generated by default as identity
        primary key,
    code varchar(50)  not null,
    name varchar(100) not null,
    constraint uk_roles_code unique (code)
);

INSERT INTO roles (code, name)
VALUES ('ROLE_ADMIN', 'Administrator'),
       ('ROLE_MANAGER', 'Manager'),
       ('ROLE_STAFF', 'Staff');

create table employee_positions
(
    id                           bigint generated by default as identity
        primary key,
    code                         varchar(50)  not null,
    display_name                 varchar(100) not null,
    requires_exclusive_placement boolean      not null,

    constraint uk_employee_positions_code unique (code)
);

create table employee_position_permissions
(
    position_id bigint       not null,
    permission  varchar(100) not null,

    constraint pk_employee_position_permissions
        primary key (position_id, permission),

    constraint fk_epp_position
        foreign key (position_id) references employee_positions (id)
);

create table employees
(
    id            bigint generated by default as identity
        primary key,
    position_id   bigint       not null,
    first_name    varchar(255) not null,
    last_name     varchar(255) not null,
    contact_email         varchar(255) not null,
    mobile_number varchar(255) not null,

    street        varchar(255) not null,
    street_number varchar(255),
    city          varchar(255) not null,
    zip_code      varchar(255) not null,

    hire_date     date         not null,
    is_active     boolean      not null,

    constraint fk_employees_position_id
        foreign key (position_id) references employee_positions (id),
    constraint uk_employees_email unique (contact_email)
);

create table employee_assignments
(
    id            bigint generated by default as identity primary key,
    employee_id   bigint      not null,
    house_unit_id bigint      not null,
    status        varchar(30) not null,
    start_date    date        not null,
    end_date      date,

    constraint fk_employee_assignments_employee
        FOREIGN KEY (employee_id) REFERENCES employees (id),

    constraint fk_employee_assignments_house_unit
        FOREIGN KEY (house_unit_id) REFERENCES house_units (id),


    constraint chk_employee_assignments_status
        check ((status)::text = any
               ((array [
                   'ACTIVE'::character varying,
                   'COMPLETED'::character varying,
                   'TERMINATED'::character varying,
                   'CANCELLED'::character varying
                   ])::text[])),

    constraint chk_employee_assignments_date_range
        CHECK (end_date IS NULL OR end_date >= start_date)
);

create index idx_assignment_employee
    ON employee_assignments (employee_id);

create index idx_assignment_house_unit
    ON employee_assignments (house_unit_id);

create table employee_placements
(
    id            bigint generated by default as identity primary key,
    employee_id   bigint  not null,
    house_unit_id bigint  not null,
    start_Date_Time    timestamp    not null,
    end_Date_Time      timestamp,
    reason        varchar not null
        constraint chk_employee_placement_reason
            check ((reason)::text = ANY
                   ((ARRAY [
                       'TEMPORARY_COVERAGE':: character varying
                       ])::text[])
                ),

    constraint fk_employee_placements_employee
        foreign key (employee_id) references employees (id),
    constraint fk_employee_placements_house_unit
        foreign key (house_unit_id) references house_units (id)
);


CREATE TABLE users
(
    id          bigint generated by default as identity primary key,
    employee_id bigint       not null unique,
    username    varchar(255) not null,
    password    varchar(255) not null,
    email       varchar(255) not null,
    role        varchar(20)  not null,
    active      boolean      not null default true,

    constraint fk_users_employee
        FOREIGN KEY (employee_id) REFERENCES employees (id),
    constraint uk_users_username UNIQUE (username),
    constraint uk_users_email UNIQUE (email)
);



