-- =================================================================
-- DATABASE SCHEMA CONVENTIONS
-- =================================================================
-- Table layout:
--   1. Columns first
--   2. Unique constraints
--   3. Foreign keys
--   4. Check constraints
--   5. Indexes after the table definition
--
-- Naming:
--   Primary key column: id
--   Public API identifier: public_id
--
-- Constraints:
--   Primary key:
--     id bigint generated by default as identity primary key
--
--   Unique:
--     constraint uk_<table>_<column> unique (<column>)
--
--   Foreign key:
--     constraint fk_<table>_<referenced_table_or_column>
--         foreign key (<column>) references <referenced_table> (id)
--
--   Check:
--     constraint chk_<table>_<rule>
--         check (...)
--
-- Indexes:
--   create index idx_<table>_<column_or_purpose>
--       on <table> (<column>);
--
-- Rules:
--   - Use timestamptz for Instant-based fields.
--   - Do not add normal indexes for columns already covered by unique constraints.
--   - Keep constraint and index names stable.
-- =================================================================

CREATE EXTENSION IF NOT EXISTS unaccent;

create table house_units
(
    id           bigint generated by default as identity primary key,
    public_id    uuid         not null,
    code         varchar(20)  not null,
    display_name varchar(50)  not null,
    address      varchar(255) not null,
    max_capacity integer      not null,

    constraint uk_house_units_public_id unique (public_id),
    constraint uk_house_units_code unique (code)
);

create table employee_positions
(
    id                           bigint generated by default as identity primary key,
    code                         varchar(50)  not null,
    display_name                 varchar(100) not null,
    requires_exclusive_placement boolean      not null,

    constraint uk_employee_positions_code unique (code)
);

create table employee_position_permissions
(
    position_id bigint       not null,
    permission  varchar(100) not null,

    constraint pk_employee_position_permissions
        primary key (position_id, permission),

    constraint fk_epp_position
        foreign key (position_id) references employee_positions (id)
);

create table employees
(
    id            bigint generated by default as identity primary key,
    public_id     uuid         not null,
    position_id   bigint       not null,
    first_name    varchar(255) not null,
    last_name     varchar(255) not null,
    contact_email varchar(255) not null,
    mobile_number varchar(255) not null,

    street        varchar(255) not null,
    street_number varchar(255),
    city          varchar(255) not null,
    zip_code      varchar(255) not null,

    hire_date     date         not null,
    is_active     boolean      not null,

    constraint fk_employees_position_id
        foreign key (position_id) references employee_positions (id),

    constraint uk_employees_email unique (contact_email),
    constraint uk_employees_public_id unique (public_id)
);

create table beneficiaries
(
    -- PK
    id                        bigint generated by default as identity primary key,

    -- Core identity
    public_id                 uuid         not null,
    first_name                varchar(255) not null,
    last_name                 varchar(255) not null,
    amka                      varchar(11)  not null,
    date_of_birth             date         not null,

    -- Status / classification
    is_active                 boolean      not null,
    discharge_date            date,
    discharge_reason          varchar(500),
    discharged_by_employee_id bigint,
    house_unit_id             bigint       not null,

    -- Permanent address
    perm_street               varchar(255) not null,
    perm_street_number        varchar(255),
    perm_city                 varchar(255) not null,
    perm_zip_code             varchar(255) not null,

    -- Emergency contact
    emergency_first_name      varchar(255) not null,
    emergency_last_name       varchar(255) not null,
    emergency_relationship    varchar(255) not null,
    emergency_mobile_number   varchar(255),
    emergency_landline_phone  varchar(255),
    emergency_email           varchar(255),
    emergency_street          varchar(255) not null,
    emergency_street_number   varchar(255),
    emergency_city            varchar(255) not null,
    emergency_zip_code        varchar(255) not null,

    constraint uk_beneficiaries_public_id unique (public_id),
    constraint uk_beneficiaries_amka unique (amka),

    constraint fk_beneficiaries_house_unit
        foreign key (house_unit_id) references house_units (id),

    constraint fk_beneficiaries_discharged_by_employee
        foreign key (discharged_by_employee_id) references employees (id),

    constraint chk_beneficiaries_emergency_relationship
        check (emergency_relationship in (
                                          'PARENT', 'SIBLING', 'OTHER_RELATIVE', 'FRIEND', 'SOCIAL_WORKER', 'OTHER'
            )),

    constraint chk_beneficiaries_discharge_fields_consistency
        check (
            (is_active = true
                and discharge_date is null
                and discharge_reason is null
                and discharged_by_employee_id is null)
                or
            (is_active = false
                and discharge_date is not null
                and discharge_reason is not null
                and discharged_by_employee_id is not null)
            )
);

create table allergies
(
    id             bigint generated by default as identity primary key,
    public_id      uuid         not null,
    beneficiary_id bigint       not null,
    substance      varchar(255) not null,
    severity       varchar(30)  not null,
    reaction       varchar(255) not null,

    constraint uk_allergies_public_id unique (public_id),

    constraint fk_allergies_beneficiary
        foreign key (beneficiary_id) references beneficiaries (id) on delete cascade,

    constraint chk_allergies_severity
        check (severity in ('LOW', 'MEDIUM', 'HIGH'))
);

create table medications
(
    id                   bigint generated by default as identity primary key,
    public_id            uuid         not null,
    beneficiary_id       bigint       not null,
    administration_times varchar(255) not null,
    dosage               varchar(255) not null,
    frequency            varchar(255) not null,
    instructions         varchar(255),
    name                 varchar(255) not null,

    constraint uk_medications_public_id unique (public_id),

    constraint fk_medication_beneficiary
        foreign key (beneficiary_id) references beneficiaries (id) on delete cascade
);

create table legal_representatives
(
    id             bigint generated by default as identity primary key,
    first_name     varchar(255) not null,
    last_name      varchar(255) not null,
    afm            varchar(11)  not null,
    type           varchar(255) not null,
    mobile_number  varchar(20),
    landline_phone varchar(20),
    email          varchar(255),
    notes          text,

    constraint uk_legal_representatives_afm unique (afm),
    constraint uk_legal_representatives_email unique (email),

    constraint chk_legal_representatives_type
        check (type in ('JUDICIAL_SUPPORTER', 'LEGAL_GUARDIAN', 'PUBLIC_AUTHORITY', 'OTHER'))
);

create table beneficiary_legal_representatives
(
    beneficiary_id          bigint not null,
    legal_representative_id bigint not null,

    constraint pk_beneficiary_legal_representatives
        primary key (beneficiary_id, legal_representative_id),

    constraint fk_beneficiary_legal_representatives_beneficiary
        foreign key (beneficiary_id)
            references beneficiaries (id)
            on delete cascade,

    constraint fk_beneficiary_legal_representatives_legal_representative
        foreign key (legal_representative_id)
            references legal_representatives (id)
            on delete cascade
);

create table employee_assignments
(
    id            bigint generated by default as identity primary key,
    public_id     uuid        not null,
    employee_id   bigint      not null,
    house_unit_id bigint      not null,
    status        varchar(30) not null,
    start_date    date        not null,
    end_date      date,

    constraint uk_employee_assignments_public_id unique (public_id),

    constraint fk_employee_assignments_employee
        foreign key (employee_id) references employees (id),

    constraint fk_employee_assignments_house_unit
        foreign key (house_unit_id) references house_units (id),

    constraint chk_employee_assignments_status
        check (status in ('ACTIVE', 'COMPLETED', 'TERMINATED', 'CANCELLED')),

    constraint chk_employee_assignments_date_range
        check (end_date is null or end_date >= start_date)
);

create index idx_assignment_employee
    on employee_assignments (employee_id);

create index idx_assignment_house_unit
    on employee_assignments (house_unit_id);

create table employee_placements
(
    id            bigint generated by default as identity primary key,
    public_id     uuid        not null,
    employee_id   bigint      not null,
    house_unit_id bigint      not null,
    start_date    date        not null,
    end_date      date,
    reason        varchar(30) not null,

    constraint uk_employee_placements_public_id unique (public_id),

    constraint fk_employee_placements_employee
        foreign key (employee_id) references employees (id),

    constraint fk_employee_placements_house_unit
        foreign key (house_unit_id) references house_units (id),

    constraint chk_employee_placement_reason
        check (reason in ('TEMPORARY_COVERAGE'))
);

create table users
(
    id          bigint generated by default as identity primary key,
    public_id   uuid         not null,
    employee_id bigint       not null,
    username    varchar(255) not null,
    password    varchar(255) not null,
    email       varchar(255) not null,
    role        varchar(20)  not null,
    active      boolean      not null default true,

    constraint uk_users_public_id unique (public_id),
    constraint uk_users_employee_id unique (employee_id),
    constraint uk_users_username unique (username),
    constraint uk_users_email unique (email),

    constraint fk_users_employee
        foreign key (employee_id) references employees (id),

    constraint chk_users_role
        check (role in ('ADMIN', 'STAFF'))
);

create table refresh_tokens
(
    id                          bigint generated by default as identity primary key,
    public_id                   uuid         not null,
    token_hash                  varchar(255) not null,
    user_id                     bigint       not null,
    created_at                  timestamptz  not null,
    expires_at                  timestamptz  not null,
    revoked_at                  timestamptz,
    revocation_reason           varchar(50),
    replaced_by_token_public_id uuid,
    user_agent                  varchar(512),
    ip_address                  varchar(64),

    constraint uk_refresh_tokens_public_id unique (public_id),
    constraint uk_refresh_tokens_token_hash unique (token_hash),

    constraint fk_refresh_tokens_user
        foreign key (user_id) references users (id),

    constraint chk_refresh_tokens_revocation_reason
        check (revocation_reason in (
                                     'LOGOUT',
                                     'PASSWORD_CHANGE',
                                     'USER_DEACTIVATION',
                                     'ADMIN_REVOKE',
                                     'ROTATED',
                                     'REUSE_DETECTED'
            ))
);

create index idx_refresh_tokens_user_id
    on refresh_tokens (user_id);

create table audit_logs
(
    id                 bigint generated by default as identity primary key,
    public_id          uuid         not null,
    action             varchar(100) not null,
    entity_type        varchar(100) not null,
    entity_public_id   uuid,
    user_public_id     uuid,
    employee_public_id uuid,
    ip_address         varchar(100),
    user_agent         varchar(500),
    occurred_at        timestamptz  not null,
    outcome            varchar(50)  not null,
    metadata           jsonb,

    constraint uk_audit_logs_public_id unique (public_id)
);

create index idx_audit_logs_action
    on audit_logs (action);

create index idx_audit_logs_entity
    on audit_logs (entity_type, entity_public_id);

create index idx_audit_logs_user
    on audit_logs (user_public_id);

create index idx_audit_logs_employee
    on audit_logs (employee_public_id);

create index idx_audit_logs_occurred_at
    on audit_logs (occurred_at desc);

create table password_reset_tokens
(
    id         bigint generated by default as identity primary key,
    token_hash varchar(64) not null,
    user_id    bigint      not null,
    created_at timestamptz not null,
    expires_at timestamptz not null,
    used_at    timestamptz,

    constraint uk_password_reset_tokens_token_hash unique (token_hash),

    constraint fk_password_reset_tokens_user
        foreign key (user_id) references users (id)
);

create index idx_password_reset_tokens_user_id
    on password_reset_tokens (user_id);