create table beneficiaries
(
    date_of_birth            date         not null,
    is_active                boolean      not null,
    id                       bigint generated by default as identity
        primary key,
    amka                     varchar(11)  not null
        constraint uk_beneficiaries_amka unique,
    emergency_city           varchar(255) not null,
    emergency_email          varchar(255),
    emergency_first_name     varchar(255) not null,
    emergency_landline_phone varchar(255),
    emergency_last_name      varchar(255) not null,
    emergency_mobile_number  varchar(255),
    emergency_number         varchar(255),
    emergency_relationship   varchar(255) not null
        constraint chk_beneficiaries_emergency_relationship
            check ((emergency_relationship)::text = ANY
        ((ARRAY ['PARENT':: character varying, 'SIBLING':: character varying, 'OTHER_RELATIVE':: character varying, 'FRIEND':: character varying, 'SOCIAL_WORKER':: character varying, 'OTHER':: character varying])::text[])
) ,
    emergency_street         varchar(255) not null,
    emergency_zip            varchar(255) not null,
    first_name               varchar(255) not null,
    house_unit               varchar(255) not null
        constraint chk_beneficiaries_house_unit
            check ((house_unit)::text = ANY
                   ((ARRAY ['UNIT_A'::character varying, 'UNIT_B'::character varying, 'UNIT_C'::character varying])::text[])),
    last_name                varchar(255) not null,
    legal_email              varchar(255),
    legal_first_name         varchar(255),
    legal_landline_phone     varchar(255),
    legal_last_name          varchar(255),
    legal_mobile_number      varchar(255),
    legal_notes              varchar(255),
    legal_type               varchar(255)
        constraint chk_beneficiaries_legal_type
            check ((legal_type)::text = ANY
                   ((ARRAY ['JUDICIAL_SUPPORTER'::character varying, 'LEGAL_GUARDIAN'::character varying, 'PUBLIC_AUTHORITY'::character varying, 'OTHER'::character varying])::text[])),
    perm_city                varchar(255) not null,
    perm_number              varchar(255) not null,
    perm_street              varchar(255) not null,
    perm_zip                 varchar(255) not null
);

create table allergies
(
    beneficiary_id bigint       not null
        constraint fk_allergies_beneficiary
            references beneficiaries (id),
    id             bigint generated by default as identity
        primary key,
    reaction       varchar(255) not null,
    severity       varchar(255) not null
        constraint chk_allergies_severity
            check ((severity)::text = ANY
        ((ARRAY ['LOW':: character varying, 'MEDIUM':: character varying, 'HIGH':: character varying])::text[])
) ,
    substance      varchar(255) not null
);

create index idx_beneficiaries_last_name
    on beneficiaries (last_name);

create table medication
(
    beneficiary_id       bigint       not null
        constraint fk_medication_beneficiary
            references beneficiaries (id),
    id                   bigint generated by default as identity
        primary key,
    administration_times varchar(255) not null,
    dosage               varchar(255) not null,
    frequency            varchar(255) not null,
    instructions         varchar(255),
    name                 varchar(255) not null
);

create table roles
(
    id          bigint generated by default as identity
        primary key,
    description varchar(255),
    name        varchar(255) not null
        constraint uk_roles_name unique
        constraint chk_roles_name
            check ((name)::text = ANY
        ((ARRAY ['PRESIDENT':: character varying, 'SECRETARY':: character varying, 'CAREGIVER':: character varying, 'PSYCHIATRIST':: character varying, 'PSYCHOLOGIST':: character varying, 'SOCIAL_WORKER':: character varying, 'FITNESS_INSTRUCTOR':: character varying, 'EDUCATOR':: character varying, 'HOUSE_MANAGER':: character varying])::text[])
)
    );

create table users
(
    active     boolean      not null,
    id         bigint generated by default as identity
        primary key,
    email      varchar(255) not null
        constraint uk_users_email unique,
    first_name varchar(255) not null,
    last_name  varchar(255) not null,
    mobile     varchar(255),
    password   varchar(255) not null,
    username   varchar(255) not null
        constraint uk_users_username unique
);

create table user_roles
(
    role_id bigint not null
        constraint fk_user_roles_role
            references roles (id),
    user_id bigint not null
        constraint fk_user_roles_user
            references users (id),
    constraint pk_user_roles primary key (role_id, user_id)
);


